### PR TITLE
don't use panics as flow-control

### LINKED ISSUE #228: Don't `panic()`
Several of our current execution error paths end in `panic` where they should end in `log.Fatalf()` instead because they're not recoverable errors and stack traces are unfriendly toward users. `grep -r "panic" . | grep -v "./vendor"` shows:

```
./db_service/db_service.go:			panic(fmt.Sprintf("Error migrating database: %s", err.Error()))
./db_service/setup_db.go:		panic("DB_HOST, DB_USERNAME and DB_PASSWORD are required environment variables.")
./brokerapi/brokers/models/db.go:		panic(err)
./brokerapi/brokers/models/db.go:			panic(err)
./brokerapi/brokers/broker_base/broker_base.go:	panic("Can't check last operation on a synchronous service")
```

The last one SHOULD NOT cause a panic, but instead an error message. The connection should error rather than crash due to a user mistake.

### PR DESCRIPTION
**Pull request by josephlewis42**
Fixes #228. Rather than using `panic` as a flow-control device, use `error` instead.

This mostly affects tests, which I've updated and re-ran to validate.

### CODE REVIEW

File: brokerapi/brokers/models/db.go [hunk 1]
```diff
@@ -24,30 +24,26 @@ type ServiceBindingCredentials ServiceBindingCredentialsV1
 
 // GetOtherDetails returns an unmarshaled version of the OtherDetails field
 // or panics.
```
Comment (mattysweeps) [inline brokerapi/brokers/models/db.go]: or errors, (also I don't know if you need to say "or errors")
